package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/anggaraswn/gqlgen-todos/graph/model"
)

// CreateStore is the resolver for the createStore field.
func (r *mutationResolver) CreateStore(ctx context.Context, input model.NewStore) (*model.Store, error) {
	panic(fmt.Errorf("not implemented: CreateStore - createStore"))
}

// UpdateStore is the resolver for the updateStore field.
func (r *mutationResolver) UpdateStore(ctx context.Context, input model.NewStore) (*model.Store, error) {
	panic(fmt.Errorf("not implemented: UpdateStore - updateStore"))
}

// Stores is the resolver for the stores field.
func (r *queryResolver) Stores(ctx context.Context) ([]*model.Store, error) {
	panic(fmt.Errorf("not implemented: Stores - stores"))
}

// Store is the resolver for the store field.
func (r *queryResolver) Store(ctx context.Context, id *string, name *string) (*model.Store, error) {
	panic(fmt.Errorf("not implemented: Store - store"))
}
